from enum import Enum

from backend.app.schemas.common import APIModel


class ErrorCode(str, Enum):
    UNSUPPORTED_VIDEO_CODEC = "UNSUPPORTED_VIDEO_CODEC"
    INVALID_VIDEO = "INVALID_VIDEO"
    VIDEO_TOO_LARGE = "VIDEO_TOO_LARGE"
    VIDEO_TOO_SHORT = "VIDEO_TOO_SHORT"
    VIDEO_TOO_LONG = "VIDEO_TOO_LONG"
    MODEL_INITIALIZATION_FAILED = "MODEL_INITIALIZATION_FAILED"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"
    NO_FACE_DETECTED = "NO_FACE_DETECTED"
    INSUFFICIENT_VALID_DATA = "INSUFFICIENT_VALID_DATA"
    ANALYSIS_NOT_FOUND = "ANALYSIS_NOT_FOUND"
    EXPORT_FAILED = "EXPORT_FAILED"
    INVALID_CONFIG = "INVALID_CONFIG"
    CANCELLED = "CANCELLED"
    ANALYSIS_NOT_READY = "ANALYSIS_NOT_READY"
    LIVE_SESSION_NOT_FOUND = "LIVE_SESSION_NOT_FOUND"
    LIVE_SESSION_CLOSED = "LIVE_SESSION_CLOSED"


class APIErrorBody(APIModel):
    code: str
    message: str
    details: dict = {}


class APIErrorResponse(APIModel):
    error: APIErrorBody
